install:
  - sudo apt-get update
  - sudo apt-get install qt5-default qttools5-dev-tools qtmultimedia5-dev

script:
  - cd Server
  - qmake -project
  - qmake QueleaServer.pro
  - make
  - cd ../Client
  - qmake -project
  - qmake QueleaClient.pro
  - make