#ifndef CODES_H
#define CODES_H

enum {PING, CONNECTED, AUTH_REQUEST, AUTH_RESPONSE, CONTACTS_REQUEST,
      CONTACTS_RESPONSE, MESSAGE_TO_CHAT, MESSAGE_TO_SERVER, MESSAGE_TO_CLIENT, DR_TO_SERVER, DR_TO_CLIENT,
      FILE_REQUEST_TO_SERVER,FILE_REQUEST_TO_CLIENT, FILE_RESPONSE_TO_SERVER, FILE_RESPONSE_TO_CLIENT};

#endif
