name: Server & Client build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build Server 
      run: cd Server && qmake -project && qmake QueleaServer.pro && make
    - name: build Client
      run: cd ../Client && qmake -project && qmake QueleaClient.pro && make
